"""empty message

Revision ID: 8d33349fce3b
Revises: 5ba5ee931f50
Create Date: 2024-11-28 20:23:15.654228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d33349fce3b'
down_revision: Union[str, None] = '5ba5ee931f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('date', sa.Date(), nullable=False))
    op.alter_column('attendances', 'comment',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index('ix_attendances_attendance_date', table_name='attendances')
    op.create_index(op.f('ix_attendances_date'), 'attendances', ['date'], unique=False)
    op.drop_column('attendances', 'attendance_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('attendance_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_attendances_date'), table_name='attendances')
    op.create_index('ix_attendances_attendance_date', 'attendances', ['attendance_date'], unique=False)
    op.alter_column('attendances', 'comment',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('attendances', 'date')
    # ### end Alembic commands ###
